os: linux
dist: bionic

services:
  - docker

language: go
go:
  - 1.14.x

branches:
  only:
    - master

jobs:
  include:
    - stage: CI
      name: "Clean code"
      script:
        - make lint
    - name: "Unit tests"
      script:
        - make unittest
    - name: Build
      script:
        - make build
    - stage: CD
      name: Release
      script:
        - echo "Hi"
