os: linux
dist: bionic

# services:
#   - docker

language: go
go:
  - 1.14.x

branches:
  only:
    - master

# stages:
#   - CI
#   - name: CD
#     if: 

jobs:
  include:
    - stage: CI
      name: "Clean code"
      script:
        - make lint
    - name: "Unit tests"
      script:
        - make unittest

    - stage: CD
      name: Build
      script:
        - make build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
