os: linux
dist: bionic

language: go
go:
  - 1.14.x

git:
  quiet: true

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/

jobs:
  include:
    - stage: Validate
      name: "Clean code"
      script:
        - make lint
    - name: "Unit tests"
      script:
        - make unittest
    - stage: Release
      name: Build
      script:
        - make build_linux
        - zip kubegraph_linux_amd64.zip ./kubegraph
        - make build_darwin
        - zip kubegraph_darwin_amd64.zip ./kubegraph
        - make build_win
        - zip kubegraph_win_amd64.zip ./kubegraph
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: 
            - kubegraph_linux_amd64.zip
            - kubegraph_darwin_amd64.zip
            - kubegraph_win_amd64.zip
          skip_cleanup: true
          prerelease: true
          on:
            tags: true
            condition: $TRAVIS_TAG =~ .*rc[0-9]+$
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file: 
            - kubegraph_linux_amd64.zip
            - kubegraph_darwin_amd64.zip
            - kubegraph_win_amd64.zip
          skip_cleanup: true
          prerelease: false
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$