os: linux
dist: bionic

services:
  - docker

language: go
go:
  - 1.14.x

branches:
  only:
    - master

stages:
  - name: CI
    jobs:
      include:
        - name: Verify clean code
          script:
            - make lint
        - name: Run unit tests
          script:
            - make unittest
        - name: Build binary
          script:
            - make build
